version: "3.8"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wp
    ports:
      - "443:443"
    networks:
      - int_net

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wp
    ports:
      - "9000:9000"
    networks:
      - int_net

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - int_net

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/vduchi/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/vduchi/data/wordpress
      o: bind


networks:
  int_net:
    driver: bridge
