version: "3.8"

services:
  mariadb:
    build: requirements/mariadb
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - net

  nginx:
    build: requirements/nginx
    container_name: web
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wp
    ports:
      - "443:443"
    networks:
      - net

  wordpress:
    build: requirements/wordpress
    container_name: wp
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wp
    ports:
      - "9000:9000"
    networks:
      - net

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/vduchi/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/vduchi/data/wordpress
      o: bind

networks:
  net:
    driver: bridge
